version: "3.4"

services:
  postgres:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "vatly"

volumes:
  db_volume: null
